
<div
	class="info flex flex-col w-full md:w-7/12 sm:w-full px-12 md:p-0 sm:p-12  tracking-in-expand  mt-10 lg:mt-32  md:mt-20 sm:mt-4 mx-auto"
>
	<div
		class="titles text-4xl md:text-4xl lg:text-5xl xl:text-7xl text-white mb-4"
	>
		<h1>Full-stack web developer,</h1>
		<h1>Security consultant,</h1>
		<h1>Cloud expert</h1>
	</div>
	<p class="w-full md:w-2/3 lg:w-1/2	 tracking-wide mb-4">
		Hey👋, I'm Mathias, a Norwegian based designer and software developer
		specializing in full-stack web development.
	</p>
	<hr class="w-full md:w-2/3 lg:w-1/2	 tracking-wide mb-4 text-secondary" />
	<div class=" flex mb-4 items-center gap-4 ">
		<a href="https://github.com/Azzpr">
			<img src="/icons/github.svg " class="h-12 cursor-pointer " alt="" />
		</a>
		<a href="https://www.linkedin.com/in/mathias-%C3%B6dlund-4a3a2b232">
			<img src="/icons/linkedin.svg " class="h-12 cursor-pointer " alt="" />
		</a>
		<a href="https://www.fiverr.com/thomasbents">
			<img src="/icons/fiverr.svg " class="h-12 cursor-pointer " alt="" />
		</a>
	</div>
	<a href="/about">
		<button class="btn btn-primary btn-outline w-full md:w-[200px] sm:w-full"
			>Learn more</button
		>
	</a>
</div>
<style lang="scss">
	@import url('https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
	.info {
		/* font-family: 'Jost', sans-serif !important; */
	}
	.tracking-in-expand {
		-webkit-animation: tracking-in-expand 1.3s
			cubic-bezier(0.215, 0.61, 0.355, 1) both;
		animation: tracking-in-expand 1.3s cubic-bezier(0.215, 0.61, 0.355, 1) both;
	}
	/* ----------------------------------------------
 * Generated by Animista on 2022-7-11 9:43:53
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
	/**
 * ----------------------------------------
 * animation tracking-in-expand
 * ----------------------------------------
 */
	@-webkit-keyframes tracking-in-expand {
		0% {
			letter-spacing: -0.5em;
			opacity: 0;
		}
		40% {
			opacity: 0.6;
		}
		100% {
			opacity: 1;
		}
	}
	@keyframes tracking-in-expand {
		0% {
			letter-spacing: -0.5em;
			opacity: 0;
		}
		40% {
			opacity: 0.6;
		}
		100% {
			opacity: 1;
		}
	}
</style>